# Config file for automatic testing at travis-ci.org

dist: bionic
language: python
python:
  - 3.6
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U pip
    - pip install -U tox-travis
    - pip install flake8

# Command to run tests, e.g. python setup.py test
script: 
    - tox
    - flake8
