# Config file for automatic testing at travis-ci.org

language: python

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

python:
  - 3.6
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U pip
    - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
